services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro


  node-exporter:
    image: prom/node-exporter
    pid: host
    volumes:
      - /:/host:ro
    command:
      - --path.rootfs=/host
    ports:
      - "9100:9100"


  dcgm-exporter:
    image: nvcr.io/nvidia/k8s/dcgm-exporter:4.5.2-4.8.1-ubuntu22.04
    gpus: all
    cap_add:
      - SYS_ADMIN
    ports:
      - "9400:9400"


  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml:ro

